<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName Condition="'$(CI)'!='true'">local.KbinXml.Net</AssemblyName>
    <Configurations>Debug;Release;DebugLog</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework) != 'netstandard2.0'">
    <IsTrimmable>true</IsTrimmable>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Speed</OptimizationPreference>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StackTraceSupport>false</StackTraceSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <XmlResolverIsNetworkingEnabledByDefault>false</XmlResolverIsNetworkingEnabledByDefault>
  </PropertyGroup>

  <PropertyGroup Label="PackageSetting">
    <Authors>NKZsmos</Authors>
    <RepositoryUrl>https://github.com/Milkitic/KBinXml.Net</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/Milkitic/KBinXml.Net</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Copyright>Copyright © NKZsmos 2022-2025</Copyright>
    <Description>High performance .NET library for encoding/decoding Konami's binary XML format.</Description>
    <PackageTags>komani</PackageTags>
  </PropertyGroup>

  <PropertyGroup Label="MinVerSetting">
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <MinVerMinimumMajorMinor>1.0</MinVerMinimumMajorMinor>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration) == 'Release' ">
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='DebugLog'">
    <DefineConstants>$(DefineConstants);USELOG</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="$(TargetFramework) == 'netstandard2.0'">
    <PackageReference Include="System.Memory" Version="4.6.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <PackageReference Include="MinVer" Version="4.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
