<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;DebugLog</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.6" />
    <PackageReference Include="KbinXml.Net" Version="1.1.0" Aliases="kbin1_1" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework) != 'net48'">
    <ProjectReference Include="..\..\..\dependencies\KBinXML\KBinXML\KBinXML.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\dependencies\kbinxmlcs\kbinxmlcs\kbinxmlcs.csproj" />
    <ProjectReference Include="..\..\KbinXml.Net\KbinXml.Net.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="data\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
