<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net8.0;net9.0</TargetFrameworks>
    <LangVersion>13.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\KbinXml.Net\KbinXml.Net.csproj" />
  </ItemGroup>

</Project>
